### ISSUE TITLE
Incorrect pointer to `interface`

### ISSUE THREAD

**Issue by d-enk** [samber/go-type-to-string#2]
https://github.com/samber/go-type-to-string/blob/810c3951834a110bde702691eddfbdaf18ff581f/converter.go#L31-L32

Why?

```go
package main

import (
	"fmt"

	typetostring "github.com/samber/go-type-to-string"
)

func main() {
	type I interface {}

	fmt.Println(typetostring.GetType[I]())   // *main.I
	fmt.Println(typetostring.GetType[*I]())  // *main.I
	fmt.Println(typetostring.GetType[**I]()) // **main.I
}
```

**Comment by samber** [comment]
Without the `getInterfaceType` hack, `typetostring.GetType[interface{}]()` would return `*interface {}`.

This is a know limitation.

If you have a better way to handle this case, I would be very happy to accept your contribution!!

**Comment by d-enk** [comment]
Meant why only for `any`
What about trim `*` for all

```go
return t[1:]
```

**Comment by samber** [comment]
We cannot disable all `*`, beucase we need to differentiate `*string` et `string`.

You can disable the `getInterfaceType` hack and iterate with existing unit test.

**Comment by d-enk** [comment]
Not all `*`, only for interface. when `reflect.TypeOf(t) == nil`

**Comment by d-enk** [comment]
This behavior wasn't planned, was it?

https://play.golang.com/p/RM9X82ZRprN

**Comment by d-enk** [comment]
You are confused here

https://github.com/samber/go-type-to-string/blob/668e29203ca583ef1191bbd3f8f911731520d9b5/README.md?plain=1#L45

After 1.3.0 there will be `any`
No try to unpack interface (not only `any`)

**Comment by samber** [comment]
Yes, this is why I listed this in the "not supported yet" section.

**Comment by d-enk** [comment]
OK. I'll add an explanation of reason here too. Just

```go
type I interface {
  // ...
}
```

The same type as any other (in the context of this package)
which has its own name.
